### ISSUE TITLE
docker build 运行失败

### ISSUE THREAD

**Issue by mxdwjcty** [phplaber/yawf#1]
`
 => [4/6] RUN sudo apt-get update && sudo apt-get install -y python3-pip                                         177.3s
 => ERROR [5/6] RUN pip3 install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.douba  0.7s
------
 > [5/6] RUN pip3 install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com:
0.639 error: externally-managed-environment
0.639
0.639 × This environment is externally managed
0.639 ╰─> To install Python packages system-wide, try apt install
0.639     python3-xyz, where xyz is the package you are trying to
0.639     install.
0.639
0.639     If you wish to install a non-Debian-packaged Python package,
0.639     create a virtual environment using python3 -m venv path/to/venv.
0.639     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
0.639     sure you have python3-full installed.
0.639
0.639     If you wish to install a non-Debian packaged Python application,
0.639     it may be easiest to use pipx install xyz, which will manage a
0.639     virtual environment for you. Make sure you have pipx installed.
0.639
0.639     See /usr/share/doc/python3.12/README.venv for more information.
0.639
0.639 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
0.639 hint: See PEP 668 for the detailed specification.
------
Dockerfile:7
--------------------
   5 |     COPY requirements.txt requirements.txt
   6 |     RUN sudo apt-get update && sudo apt-get install -y python3-pip
   7 | >>> RUN pip3 install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com
   8 |
   9 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install -r requirements.txt -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com" did not complete successfully: exit code: 1
`

**Comment by phplaber** [comment]
这个报错的原因是 PEP668 未在容器中实现，通过添加选项 --break-system-packages 解决。
已更新 Dockerfile 文件，可以再试下。有问题请留言，谢谢。
